### PR TITLE
use sh -c when selecting executable

### LINKED ISSUE #3: ruby script fails with "no such file or directory" on Ubuntu 25.10
I'm using Ubuntu 25.10; I use zsh and when I try to use this, the ruby script fails with:

```
 fzf-url.rb:14:in ``': No such file or directory - command (Errno::ENOENT)
````

Somehow the backtick execution happens in a context where `command` is not available.

Using `sh -c` fixes it for me, and ought to be portable:

```
`sh -c 'command -v #{c.split.first}'`.empty?.!
````

### PR DESCRIPTION
**Pull request by dandrake**
Fixes #3: on some systems, the backtick string is executed in some context in which the shell builtin `command` is not available; using `sh -c` ensures that it is.

### CODE REVIEW

File: fzf-url.rb [hunk 1]
```diff
@@ -6,7 +6,7 @@
 
 def executable(*commands)
   commands.find do |c|
-    `command -v #{c.split.first}`.empty?.!
+    `sh -c 'command -v #{c.split.first}'`.empty?.!
```
Comment (junegunn) [inline fzf-url.rb]: Didn't know about this. A simpler workaround would be to add a meta-character (e.g. wrapping an argument with `"`) to force Ruby to rely on a shell to evaluate it.


```suggestion
    `command -v "#{c.split.first}"`.empty?.!
```

https://github.com/ruby/ruby/blob/ca23c7c404871abec5acfedf35843387148350d8/process.c#L2518-L2542

File: fzf-url.rb [hunk 2]
```diff
@@ -42,7 +42,7 @@ def extract_urls(line)
             .flat_map { |l| extract_urls(l) }.reverse.uniq
 halt 'No URLs found' if urls.empty?
 
-header = 'Press CTRL-Y to copy URL to clipboard'
+header = 'Select URL: <enter> to open, <ctrl-Y> to copy to clipboard'
```
Comment (junegunn) [inline fzf-url.rb]: This one's a bit subjective.

```suggestion
header = 'Enter: Open URL / CTRL-Y: Copy to clipboard'
```

What do you think?

Comment (dandrake) [reply fzf-url.rb]: That is indeed more subjective -- your suggestion looks fine!

File: fzf-url.rb (hunk 1 above)
Comment (dandrake) [reply fzf-url.rb]: Hrm, this is strange. Now I am not seeing this problem! 

I don't know how I triggered this before. So I'd hold off on this until I can reproduce, or decide I had somehow done something weird to the backtick string that runs `command`.

Comment (junegunn) [reply fzf-url.rb]: I could reproduce the reported problem with a Ruby installed using `apt` inside a fresh Ubuntu 25 Docker container. Maybe it depends on which Ruby installation you have, but the fix here is valid.

Comment (junegunn) [reply fzf-url.rb]: Also using this image:

```sh
docker run -it ruby:slim-trixie
```

```
irb(main):001> `command -v ruby`
(irb):1:in 'Kernel#`': No such file or directory - command (Errno::ENOENT)
        from (irb):1:in '<main>'
        from /usr/local/lib/ruby/gems/4.0.0/gems/irb-1.16.0/exe/irb:9:in '<top (required)>'
        from /usr/local/lib/ruby/4.0.0/rubygems.rb:303:in 'Kernel#load'
        from /usr/local/lib/ruby/4.0.0/rubygems.rb:303:in 'Gem.activate_and_load_bin_path'
        from /usr/local/bin/irb:25:in '<main>'
irb(main):002> `command -v "ruby"`
=> "/usr/local/bin/ruby\n"
```

**Comment by junegunn** [comment]
Merged, thanks!

**Comment by dandrake** [comment]
Interesting, I also have ruby installed via apt. But if you could reproduce it, and the quotes force using a shell, that seems like the best solution. Thanks for merging a fix!
